name: Build and Deploy

on:
  push:
    branches: [ "master" , "staging" ]

jobs:

  build-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to TGM Docker Registry
      uses: docker/login-action@v3
      with:
        registry: registry.tgm.one
        username: robot$tgm.one+github
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate Website Tag Names
      run: |
        echo "${{ steps.extract_branch.outputs.branch }}"
        if [ ${{ steps.extract_branch.outputs.branch }} = "master" ]; then
          echo "TAG_LATEST_WEBSITE=tgm-one:latest" >> $GITHUB_ENV
          echo "TAG_COMMIT_WEBSITE=tgm-one:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        elif [ ${{ steps.extract_branch.outputs.branch }} = "staging" ]; then
          echo "TAG_LATEST_WEBSITE=tgm-one-stage:latest" >> $GITHUB_ENV
          echo "TAG_COMMIT_WEBSITE=tgm-one-stage:$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        else
          exit 0
        fi

    - name: Build and push Website
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: .docker/Dockerfile
        push: true
        tags: |
          registry.tgm.one/tgm.one/${{ env.TAG_LATEST_WEBSITE }}
          registry.tgm.one/tgm.one/${{ env.TAG_COMMIT_WEBSITE }}
        cache-from: type=registry,ref=registry.tgm.one/tgm.one/${{ env.TAG_LATEST_WEBSITE }}
        cache-to: type=inline

  deploy-rancher:
    needs: [build-website]
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Redeploy Rancher
      run: |
        url='https://rancher.tgm.one'
        cluster=c-ngr6r
        token=${{ secrets.RANCHER_TOKEN }}

        redeploy() {
            local app=$1
            pod_upgrade_body=$(curl -s -u "$token" \
            -k $url/k8s/clusters/$cluster/v1/apps.deployments/$namespace/$app \
            -X GET \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Pragma: no-cache' \
            -H 'Cache-Control: no-cache' 2>&1 | sed  "s/\"cattle\.io\/timestamp\"\:\"[0-9T:Z-]*\"/\"cattle\.io\/timestamp\":\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"/g")

            curl -u "$token" \
            -k -s $url/k8s/clusters/$cluster/v1/apps.deployments/$namespace/$app \
            -X PUT \
            -H 'Accept: application/json' \
            -H 'Content-Type: application/json' \
            --data-binary "$pod_upgrade_body" --compressed
        }

        echo "${{ steps.extract_branch.outputs.branch }}"
        if [ ${{ steps.extract_branch.outputs.branch }} = "master" ]; then
            namespace=tgm-one
            redeploy "website"
        elif [ ${{ steps.extract_branch.outputs.branch }} = "staging" ]; then
            namespace=tgm-one-staging
            redeploy "tgm-one-staging"
        else
            exit 0
        fi